### ISSUE TITLE
String label problem in multiBarChart

### ISSUE THREAD

**Issue by jcrichard** [areski/python-nvd3#104]
Hi

Thanks for your work.
I have a problem. String are replaced by NaN in bar chart. See for example this code:

thanks again

    from nvd3 import multiBarChart

    # Open File for test
    output_file = open('test_multiBarChart.html', 'w')

    type = "multiBarChart"
    chart = multiBarChart(name='mygraphname', height=400, width=600)
    chart.set_containerheader("\n\n<h2>" + type + "</h2>\n\n")
    xdata = ["A", "B", "C", "D", "E", "F", "G"]
    ydata = [3, 12, -10, 5, 25, -7, 2]

    extra_serie = {"tooltip": {"y_start": "", "y_end": " cal"}}
    chart.add_serie(y=ydata, x=xdata, extra=extra_serie)

    chart.buildhtml()
    output_file.write(chart.htmlcontent)
    # ---------------------------------------

    # close Html file
    output_file.close()

**Comment by areski** [comment]
I tested your example and multiBarChart works with numeric value as xdata, 
if you want to use letter you should have a look at "discreteBarChart" https://github.com/areski/python-nvd3/blob/develop/examples/discreteBarChart.py

**Comment by jcrichard** [comment]
Yes I no but I want to use multivariate chart nit discrete bar.

It is working by removing the x-axis formating in the HTML generated
