### ISSUE TITLE
Mutlibarchart : same id error

### ISSUE THREAD

**Issue by 5ri** [areski/python-nvd3#108]
Hey looks likes you change the id in the js for`pieChart` but not for `multiBarChart`

**Comment by areski** [comment]
I'm not sure what you are referring to by `id`?

**Comment by oz123** [comment]
probably the ID of the element. I think you can specify the id, and if you don't it get's the name of the chart class. If not we should implement a patch for it.

**Comment by areski** [comment]
@oz123 @5ri Still not sure what need to be fixed, please reopen if you can provide more information
