### ISSUE TITLE
How to render HTML output in Sublime Text

### ISSUE THREAD

**Issue by BjoernLaemmerzahl** [areski/python-nvd3#109]
Hey,

fist, I am really sorry for bringing this up here, but I have no idea whereelse to post this.

I am used to work with R Studio and as I like my output to be available on a Django-based website, I started using Python more for the analytical part aswell. One of the problems I have is finding an editor similar to RStudio as it allows me to plot interactive charts just like any other output. I have not found an equivalent for Python . It would be fantastic to render to HTML output provided by python-nvd3 in Sublime. I know it is possible in IPyhon, but for a number of reasons I can't say I like working with IPython. Can you help me finding a solution for Sublime? I have been googling, but not knowing what I am looking for, I have not been successful.

Thank you for your time and patience.
I am really looking forward to use Python-NVD3.

**Comment by oz123** [comment]
Hi, 
If you are a Windows user, take a look at [PythonX,Y](http://python-xy.github.io/). 
If you are using you can go along with [Spyder](https://github.com/spyder-ide/spyder), which is the IDE component in PythonX,Y. 

RStudion borrowed many things from Spyder. Python NVD3 is very cool for websites, but for general plotting, I suggest that you look at matplotlib. 

I hope you will have fun using Python, it's much more fun than R.
