### ISSUE TITLE
Not show tooltips for discreteBarChart

### ISSUE THREAD

**Issue by rowanv** [areski/python-nvd3#112]
Is there currently a way to not show tooltips for a `discreteBarChart`? Basically the resultant chart would be in the style of this chart: http://nvd3.org/examples/discreteBar.html where it calls `tooltips(false)`. 

This would be handy because currently the way that NVD3 renders tooltips seems to allow for the tooltip to extend past the edges of the chart itself, which then means that the tooltip can be cut off for certain values.

**Comment by oz123** [comment]
@rowanv, that was an easy fix, you can now install python-nvd3 directly from github to use that feature. 

See the example how  to do it.

**Comment by oz123** [comment]
And now with a dynmic example in the docs: http://python-nvd3.readthedocs.org/en/latest/classes-doc/discrete-bar-chart.html

**Comment by rowanv** [comment]
Awesome, thanks, @oz123!

**Comment by areski** [comment]
Wow really neat :)

**Comment by oz123** [comment]
It was such an easy fix, because of @pignacio  his PR made me aware of a forgotten feature we implemented.

https://github.com/areski/python-nvd3/pull/111/files
