### ISSUE TITLE
chart.tooltipContent is not a function

### ISSUE THREAD

**Issue by SrinivasanBigData** [areski/python-nvd3#118]
Hi,
   i am getting the above exception, while i was using latest version nvd3(1.8). when i searched it on google i found the solution. The  error is present in the template html file. can you please change the chart.tooltipContent(function(key, y, e, graph) { } funtion to chart.tooltip.contentGenerator(function (obj) { return JSON.stringify(obj)})

**Comment by oz123** [comment]
Don't use nvd3 1.8 with python-nvd3. Currently it's not working. See https://github.com/areski/python-nvd3/pull/114

**Comment by SalahAdDin** [comment]
Reported here: http://stackoverflow.com/questions/35125110/django-nvd3-chart-tooltipcontent-is-not-a-function

**Comment by areski** [comment]
related to https://github.com/areski/python-nvd3/pull/128
