### ISSUE TITLE
overriding labels for discreteBarChart

### ISSUE THREAD

**Issue by kouroshparsa** [areski/python-nvd3#120]
As you can see in the code below, when the labels are too long, you do not want to display them.
There must be a way to give them values or just hide them.

```
#!/usr/bin/python
# -*- coding: utf-8 -*-
from nvd3 import discreteBarChart
import random
output_file = open('bar_chart.html', 'w')
chart = discreteBarChart(name='discreteBarChart', height=350, width=800)
nb_element = 10

xdata = list(range(nb_element))
xdata = ['x121e2423432423{}x'.format(x) for x in range(nb_element)]
ydata = [random.randint(1, 10) for i in range(nb_element)]

chart.add_serie(name="Count", y=ydata, x=xdata)
chart.show_labels(False)
chart.buildhtml()

output_file.write(chart.htmlcontent)
output_file.close()
```

**Comment by kouroshparsa** [comment]
I found a wrokaround which is rotating the labels:
```
chart.margin_bottom = 100
chart.axislist['xAxis']['rotateLabels'] = -25
```

but still sometimes you'd want the tooltip and axis values to be different so still it would be nice to have that.
Also, I just want to mention that the documentation needs a complete re-work.

**Comment by areski** [comment]
if you dont want to display them or adjust it somehow, I would advice you open a PR with some changes to make this happen on the nvd3 project, it could be a nice addition: https://github.com/novus/nvd3
I'm closing this here, as there is no much we can do.
