### ISSUE TITLE
Adding other complex graphics and other fixes

### ISSUE THREAD

**Issue by SalahAdDin** [areski/python-nvd3#121]
Hi man, first of all, thank you very much, you save my live.
So, i had a big error with you library that make me thing, why not update the d3 and nvd3 packages and change the way of get it, i mean, don't use bower, for example.

In addtion i want, well, i need implements the next chart: https://bost.ocks.org/mike/nations/, for example.

Can you give support for more complex charts? Thanks!

Other comment, i found this piece of code in python-nvd3:
```
The above code will create graph with a black text, the following will change it::
            text_white="d3.selectAll('#pieChart text').style('fill', 'white');"
            chart.add_chart_extras(text_white)
```

But, in django-nvd3 isn't easier put extras than python-nvd3, in addition many interesting pieces of code in the code aren't in the documentation, making some hard work with this packages.

Or do things like this:
```
d3.select('#chart svg')
  .append("text")
  .attr("x", 200)             
  .attr("y", 100)
  .attr("text-anchor", "middle")  
  .text("Sample Charts");
```

**Comment by areski** [comment]
It might be better to not open issue with several subject, it's harder to follow.
If you want to build nations graph, I would advice to study the code for us the plan is to support graph supported by nvd3 not any others 'http://nvd3-community.github.io/nvd3/'
My advice would be that we need to first includes nations to nvd3 before integrating it here:
https://github.com/nvd3-community/nvd3
