### ISSUE TITLE
Margin_top and Margin_bottom both not functioning in JS. 

### ISSUE THREAD

**Issue by tangsteve** [areski/python-nvd3#122]
Alter margin_top or margin_bottom isn't working properly. 

And it works nicely with Left or Right. 

```
'nv.addGraph(function() 
{var chart = nv.models.lineChart();
chart.margin({top: 30, right: 60, bottom: 20, left: 80});
var datum = data_dummy;
chart.color(d3.scale.category20().range());`
```

Actually, I simply want to adjust the top margin to put a title there. 

P.S. Love you guys it saves my life.

**Comment by areski** [comment]
I dont think chart.margin is supported, it seems that using css might be better to adjust the graph margin:
http://stackoverflow.com/questions/29736374/change-margins-and-padding-in-nvd3-chart
