### ISSUE TITLE
Adding showValues(true) to discretebar

### ISSUE THREAD

**Issue by jrburris** [areski/python-nvd3#144]
Does anyone know how to do this? I'm using flask and can get the graph to render, but I can't figur e out how to pass the showValues. here is my code:

@app.route('/nvd3/discretebarchart')
def get_nvd3_discreteBarChart():

    report_title = 'NVD3 Discrete Bar Chart'

    chart = discreteBarChart(name='discreteBarChart', height=400, width=600, showValues=True)

    xdata = ["A", "B", "C", "D", "E", "F"]
    ydata = [3, 4, 1, 4, 5, 7]

    chart.add_serie(y=ydata, x=xdata)
    chart.buildhtml()

    return render_template('nvd3/chart.html', chart=chart,
                           report_title=report_title)

**Comment by quetzaluz** [comment]
You can now utilize the `show_values` option on the develop version of this branch. Example of how you would use this new option:
```
chart = discreteBarChart(name='mygraphname', height=400, width=600, show_values=True)
```

It's exactly what you requested above, just using an underscore / snake case per python conventions.
