### ISSUE TITLE
Release new version

### ISSUE THREAD

**Issue by PetrDlouhy** [areski/python-nvd3#165]
In the `develop` branch is many improvements. @areski Would it be possible to release new version of `python-nvd3`?
Thank you very much :-)

**Comment by areski** [comment]
I think there is quite a lot of work to be done in ordered to have this ready for a release, and much likely the work on the develop branch is also out of date.
We will have to look at it, happy to have some help :+1:

**Comment by PetrDlouhy** [comment]
@areski Do you have idea, what should be done before releasing? Fix tests? Update dependencies? Merge with master?

**Comment by areski** [comment]
I think it's mainly update all the dependencies, specially make sure we use the last version of https://github.com/novus/nvd3
Finally ensure that all the tests are still passing.

**Comment by PetrDlouhy** [comment]
@areski What remains before we can release? I think, there would need to be some code cleanup:

- [ ] Update the examples under each chart type. Is there some way, how to make it automatically?
- [ ] Remove the `tooltip_condition_string` code if it is not needed anymore.
- [ ] Fix tests, which are currently broken because they expect the tooltip code.
- [ ] Test all the charts.

**Comment by areski** [comment]
Not sure what you have in mind about updating the example, the documentation will put the example from the source code to render it (eg. https://github.com/areski/python-nvd3/blob/develop/docs/source/classes-doc/discrete-bar-chart.rst)

* I just committed a fix for `tooltip_condition_string`
* I also closed that PR opened for long and needed some rework: https://github.com/areski/python-nvd3/pull/114
* also changed version of py3 to support https://github.com/areski/python-nvd3/commit/f9cb41b5deaa0d7c338764d7008a4c9a5ad50dca

Yes for the other points, it would certainly be good to fix the test :)

**Comment by PetrDlouhy** [comment]
@areski Yes, I meant that charts in the docs. They are generated from docstrings, where is example source code and example result code for each example. The result code is outdated now (and was even before the tooltip change). I would need to go through all chart types and generate new code, if there is no way to do that automatically.

**Comment by areski** [comment]
Yes the example and the doc example are different, if you find an easy way I would be happy with that, but if not don't worry, it's not too much work copying them over.

**Comment by PetrDlouhy** [comment]
I have discovered issue where the old tooltips hang over the chart after changing chart type in `django-admin-charts`. I am not sure, if this issue is problem also for `python-nvd3`. Anyway, the fix is easy - I added following command before loading the chart:

```
   d3.selectAll('.nvtooltip').remove();
```

**Comment by areski** [comment]
@PetrDlouhy I just published a new release https://pypi.org/project/python-nvd3/, let me know how this is working for you

**Comment by PetrDlouhy** [comment]
@areski Seems like I can't install it, because also `django-nvd3` needs new release.
Could you please release `django-nvd3` package from current `develop` branch (including commit https://github.com/areski/django-nvd3/commit/639300acdb014939c9f9562573f4b1425190724a)?

**Comment by areski** [comment]
@PetrDlouhy Do you think you could fix the CI tests as you did here for django-nvd3?

**Comment by PetrDlouhy** [comment]
@areski Already working on it :-)
