### ISSUE TITLE
Ipython demo does not work

### ISSUE THREAD

**Issue by observerss** [areski/python-nvd3#57]
Current Ipython demo code doesn't work

![image](https://cloud.githubusercontent.com/assets/478194/3242107/e8567d4e-f146-11e3-819a-95aadf184d64.png)

Out[3] will always be an empty space as showed above

tested with
-python2.7.7/3.4.0
-ipython 1.2.1/2.0.0/2.1.0 
-python-nvd3 0.12.2/master

change the last lline of In[3] from
```python
chart2
```
to
```python
d.HTML(str(chart2))
```
solves the problem

**Comment by oz123** [comment]
this works now
