### ISSUE TITLE
will multi chart be supported at some point?

### ISSUE THREAD

**Issue by capaneus** [areski/python-nvd3#59]
hi, 
I'm working on creating line plus stacked bar chart, seems it's supported in nv d3 model: multi chart. Just wonder will this be supported in python wrapper? If already supported, is there example some where I can reference to?

Thx!

**Comment by areski** [comment]
you should look at this example where the barchart have an option to be stacked:
https://github.com/areski/python-nvd3/blob/develop/examples/multiBarChart.py
