### ISSUE TITLE
nvd3 fork and new base project maintainer (thoughts and impact)

### ISSUE THREAD

**Issue by nehalecky** [areski/python-nvd3#80]
Hi All, very nice project. :)

We've been scoping a few js visualization libraries for supporting some interactive analysis with a Python based analysis tool. With our heavy use of IPython notebook internally for interactive sessions, we naturally discovered the`python-nvd3` library.

I wanted to get an understanding for the recent forking of the `nvd3` library, and how that might impact this project? Any thoughts and feelings, I would be interested to hear:
https://github.com/liquidpele/nvd3

Forgive me in advance if I've overlooked something already mentioned about this, it's late where I am, and I'm  :sleepy: !

Again, thank you.

**Comment by areski** [comment]
Hi, I'm closing this ticket as now the original nvd3 repo is very active and we support here nvd3 v1.7.1

**Comment by nehalecky** [comment]
Sounds good, thanks for the follow up @areski!
