### ISSUE TITLE
Chart demos are not working on read the docs

### ISSUE THREAD

**Issue by oz123** [areski/python-nvd3#88]
- scatterChart
- multiBarChartDate
- linePlusBarChart
- cumulativeLineChart
- multiBarHorizontalChart
- multiBarChart

**Comment by oz123** [comment]
* scatterChart is not working in IPython notebook

**Comment by areski** [comment]
scatterChart should now be working in IPython notebook

**Comment by areski** [comment]
In regards of RTD I didnt find what was the problem, any hint?

**Comment by oz123** [comment]
for example: http://python-nvd3.readthedocs.org/en/latest/classes-doc/multi-bar-chart.html

**Comment by areski** [comment]
yes I can see it s not working, I was asking if you have an idea why it s broken?

**Comment by oz123** [comment]
For the same reason chart in plain html don't work. Maybe changes in upsream nvd3? We 
need to carefully check.

**Comment by areski** [comment]
At the moment with v0.13.8 all the charts works on demo_all.py

On Sun, Apr 12, 2015 at 10:30 PM, Oz <notifications@github.com> wrote:

> For the same reason chart in plain html don't work. Maybe changes in
> upsream nvd3? We
> need to carefully check.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/areski/python-nvd3/issues/88#issuecomment-92121306>.
>



-- 
Kind regards,
/Areski

----
Arezqui Belaid, <areski@gmail.com>
Founder at Star2Billing (www.star2billing.com)

Tel: +34650784355
Twitter: http://twitter.com/areskib
LinkedIn: http://www.linkedin.com/in/areski

**Comment by oz123** [comment]
good work fixing all the issues. OK, if you managed to fix all the issue in plain HTML I am guessing that the code that takes care of the docs is broken.
I will look at it tomorrow.

**Comment by areski** [comment]
it was very simple to solve, the header wasn't right in the demo_all so it
was loading wrong version of nvd3
and scatterchart had change in API which was easy to solve :)

On Sun, Apr 12, 2015 at 11:06 PM, Oz <notifications@github.com> wrote:

> good work fixing all the issues. OK, if you managed to fix all the issue
> in plain HTML I am guessing that the code that takes care of the docs is
> broken.
> I will look at it tomorrow.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/areski/python-nvd3/issues/88#issuecomment-92128697>.
>



-- 
Kind regards,
/Areski

----
Arezqui Belaid, <areski@gmail.com>
Founder at Star2Billing (www.star2billing.com)

Tel: +34650784355
Twitter: http://twitter.com/areskib
LinkedIn: http://www.linkedin.com/in/areski

**Comment by oz123** [comment]
OK, we need to update the js code in  the doc strings of the classes. No really a problem. 

I will take care of it.

**Comment by oz123** [comment]
Fixed. I triggerd a build manually. The changes where made in commit 
https://github.com/areski/python-nvd3/commit/4a92fddc4a932e278a71f99eb1daac43dc484eb7

**Comment by areski** [comment]
AWESOME!!! Thanks @oz123
