### ISSUE TITLE
Outputting to pdf

### ISSUE THREAD

**Issue by PiranjaF** [areski/python-nvd3#89]
Hi, thanks for an awesome library!

I can't seem to find a way to output the graphs to .pdf or a similar format? Have you implemented that? Or is that something you've considered implementing?

**Comment by oz123** [comment]
I supposed any HTML to PDF converter can convert your output of html pages to PDF, and as such the output of this library. 
That said, NVD3 is an okayish library. If you really really need smart plotting with a really powerful api, please take a look at: 
http://mpld3.github.io/
