### ISSUE TITLE
python-nvd3 shows nothing and strange look on ipython notebook

### ISSUE THREAD

**Issue by poc7667** [areski/python-nvd3#90]
### The output html by python-nvd3 can not be shown

https://gist.github.com/poc7667/0f2203231fa6d01a3f39

### The output on iPython notebook looks terrible(it is so narrow).

![](https://i.imgur.com/1qs7xKT.png)

###CODE

	# load nvd3
	import random
	from IPython import display as d
	import nvd3
	nvd3.ipynb.initialize_javascript(use_remote=True)

	chart3=nvd3.lineWithFocusChart(name="focusChart",height=600)
	xdata = [ i['_id'] for i in DATA_SOURCE ]
	ydata = [ i['count'] for i in DATA_SOURCE ]
	chart3.add_serie(x=xdata,y=ydata,name="monthly allergic", x_is_date=True, x_axis_format="%Y/%m/%d")
	chart3.buildhtml()
	chart3

	with open('demo3.html','w') as f:    
	    f.write(chart3.htmlcontent)

###  Version of  iPython and nvd3

	% pip3 list | grep ipython                                                                                                     (git)-[master]
	ipython (3.1.0)
	python-nvd3 (0.13.8)

**Comment by oz123** [comment]
this problems should be solved in the developement branch. Can you please confirm?

**Comment by oz123** [comment]
fixed.
