### ISSUE TITLE
colon in content.html when adding additional chart attributes

### ISSUE THREAD

**Issue by ingodjango** [areski/python-nvd3#91]
Hi All,
in content.html in line 83 there is a colon at the and.
        {% if value is string and value.startswith(".") %}:

Since I  use that code:
      chart_attr['yAxis'] = str(".tickFormat(function(d){return d3.format('.2s')(d).replace('k', '%s').replace('M', '%s').replace('G', '%s')});" % (tsd, mio, mrd))

I have this colon in the generate JS and it throws an error: Uncaught SyntaxError: Unexpected token : 

Not sure if I'm doing something wrong here and the colon is needed for something other reason I connot see ...

**Comment by oz123** [comment]
Can you please put your complete code here? 
Does it work without colon?

**Comment by ingodjango** [comment]
Yes with removing the colon from content.html it works, but I'm not sure if it's needed in some other case but I suspect not ...

With complete code you mean?
Could be a lot, I think that's the relevant part:


    tsd = _(u'Tsd')
    mio = _(u'Mio')
    mrd = _(u'Mrd')
    chart_attr = {}
          
    if self.report.type.name_id not in ('pieChart',):
      chart_attr['yAxis'] = str(".tickFormat(function(d){return d3.format('.1s')(d).replace('k', '%s').replace('M', '%s').replace('G', '%s')})" % (tsd, mio, mrd))
     
    charttype = self.report.type.name_id
    data = Context({
        'charttype': charttype,
        'chartdata': self.chartdata,
        'extra': {
          'x_is_date': False,
          'x_axis_format': '', #leestring zeigt einfach nur die eingangswerte, oder BSp. formatiert als datum: %d %b %Y %H
          'tag_script_js': True,
          'jquery_on_ready': False,
          #'y_axis_format' : "function(d){return d3.format('.2s')(d).replace('k', 'Tsd').replace('M', 'Mio').replace('G', 'Mrd')}",
          #'custom_format' : True,
          'chart_attr' : chart_attr,
          },
        'additional_data' : self.data,   #das ursprungsdatenobjekt auch im template zugreifbar behalten um z.B. an den Firmennamen im Template dranzukomemn
        'original_url' : self.original_url,
        'filters' : self.ui_filter_fields,
        'verb_names': self.verb_names
        #'filters': filters,
    }  )
	
    return data

**Comment by pignacio** [comment]
@oz123 this is the issue fixed in #111, I didn't check the issue list before submitting the pull request :$

**Comment by oz123** [comment]
ok, thanks for reporting this.
