### ISSUE TITLE
rotateLabels is not found. Is there any other way to handle it now?

### ISSUE THREAD

**Issue by Oxtay** [areski/python-nvd3#96]
I noticed that the older version that I was using (0.11.0) allowed for '.rotateLabels()' to be set for creating xAxis and yAxis but having updated to the latest version, this no longer works. 

Is there now a different way of doing something like this? I was not able to find any mention of it anywhere.
Thanks!

**Comment by mgx2** [comment]
Oxtay, it seems like you are using my fork of python-nvd3. Some time back, I added rotateLabels as an option, as shown in this commit: https://github.com/mgx2/python-nvd3/commit/421e071a37ed16fdf989ddac3ef585a512dd0fa9

**Comment by AlexejStukov** [comment]
Another option would be setting `chart_attr={"xAxis": ".rotateLabels(45)"}`.

**Comment by babak77** [comment]
In `content.html` file there is a `:` which causes the `Javascript` error when using `chart_attr={"xAxis": ".rotateLabels(25)"}`
You should delete the `:` at the end of the `if` statement : 
```
{# add custom chart attributes #}
        {% for attr, value in chart.chart_attr.items() %}
            {% if value is string and value.startswith(".") %}:
                chart.{{ attr }}{{ value }};
            {% else %}
                chart.{{ attr }}({{ value }});
```
