### ISSUE TITLE
color_category not handled in pieChart

### ISSUE THREAD

**Issue by romainx** [areski/python-nvd3#97]
Hello,

I have found a small bug. The `color_category`param is not taken into account in `pieChart`. This is due to a missing section in the `piechart.html` template overriding the default.
Adding this section solves the problem.
```Jinja
{% if not chart.color_list and chart.color_category %}
        chart.color(d3.scale.{{ chart.color_category }}().range());
{% endif %}
```

**Comment by areski** [comment]
Could you send a Pull Request with the patch?

**Comment by romainx** [comment]
Done #98 :-)

**Comment by areski** [comment]
Thanks for the work

**Comment by romainx** [comment]
You're welcome
It looks great now on my blog with `category20c` :-)
Check this out: http://aubonroman.com/stats.html

**Comment by areski** [comment]
c'est très élégant :)

On Tue, Aug 4, 2015 at 11:45 PM, Romain X. <notifications@github.com> wrote:

> You're welcome
> It looks great now on my blog with category20c :-)
> Check this out: http://aubonroman.com/stats.html
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/areski/python-nvd3/issues/97#issuecomment-127771423>.
>



-- 
Kind regards,
/Areski

----
Arezqui Belaid, <areski@gmail.com>
Founder at Star2Billing (www.star2billing.com)

Tel: +34650784355
Twitter: http://twitter.com/areskib
LinkedIn: http://www.linkedin.com/in/areski

**Comment by romainx** [comment]
:-D
