### ISSUE TITLE
show axis labels in lineChart

### ISSUE THREAD

**Issue by naturegirl** [areski/python-nvd3#99]
Hey,

does python-nvd3 support showing the axis labels for line Charts? I'm using the `create_x_axis()` function as found in the documention to specify the label name, but noticed that in the underlying generated D3 code, `showLabels(true)` is not called to enable them.

When digging into the source code, I also found [this](https://github.com/areski/python-nvd3/blob/a2817c9ebbdf2d585c17d4d2681bbbeea0caace8/nvd3/templates/piechart.html#L24-L25) comment suggesting it's only supported in the pieChart.

Would it be possible to add axis label support to the line chart, or could you point me to an example how to enable it? Thanks guys!

**Comment by areski** [comment]
I think `showlabels` only work for piechart, you might be interested in tooltip maybe
